spring:
  application:
   name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/Shilpa Ranjan/Documents/Capstone-Project-ShilpaRanjan/local-git-repo

server:
  port: 9999

logging:
 level:
  org:
   springframework: DEBUG