spring:
  application:
   name: api-gateway
  cloud:
    gateway:
      routes:
       - id: booking-ms
         uri: lb://booking-ms
         predicates: Path=/booking/**
       - id: payment-ms
         uri: lb://payment-ms
         predicates: Path=/payment/**
       - id: flight-data-ms
         uri: lb://flight-data-ms
         predicates: Path=/flight/**

server:
  port: 8888
